architecture:
  version: 0.3
  subtree:
    - name: fpga_system
      local:
      
        - name: DRAM
          class: DRAM
          attributes:
            type: LPDDR4
            workd_bits: 8           # INT8 elements
            block_size: 16          # 16 elements per access = 16 bytes
            bandwidth: 25.6        # GB/s  (typical LPDDR4x)
        - name: GlobalBuffer
          class: SRAM
          attributes:
            technology: "45nm"
            width: 64              # 64-bit read/write bus (8 × INT8)
            depth: 32768           # 32768 × 8 × 1 byte =
            datawidth: 8
            word_bits: 8
            block_size: 8          # 8 elements per SRAM access
            n_rdwr_ports: 2
        - name: RegisterFile
          class: regfile
          attributes:
            technology: "45nm"
            depth: 16              # 16 × INT8 = 16 bytes
            width: 16
            datawidth: 8
            word_bits: 8
            n_rdwr_ports: 2
        - name: MAC
          class: intmac
          attributes:
            technology: "45nm"
            datawidth: 8
            word_bits: 8
